# SPDX-FileCopyrightText: 2026 Institute of Radiation Physics, Helmholtz-Zentrum Dresden-Rossendorf
#
# SPDX-License-Identifier: MIT

"""Local MCP-side driver for the real-cluster connectivity check.

Three modes:

* ``--setup`` creates a private room on the homeserver using the local account
  (see ``scripts/mas_login.py``), generates the shared RCP secret, and prints
  the two values to export on the cluster before running
  ``scripts/cluster_simclient.sh``.  State is saved to ``--state`` so ``--run``
  can pick it up.

* ``--run`` drives the real MCP stdio server (``python -m pic_agentic.server``)
  and calls the ``hello`` tool, retrying until the cluster simclient acks or
  ``--wait-s`` elapses.

* ``--submit --picmi-script <path>`` calls the M2 ``submit_simulation`` tool
  with a PICMI script instead, and reports the ``sim_id`` and coarse state.
  The server needs the ``[sim]`` extra on the machine running this driver
  (``PIC_AGENTIC_PICONGPU_PYTHON`` may point at another interpreter).

* ``--watch`` reads the RCP room and prints the lifecycle events
  (``simulation.submitted``/``workflow.finished``/``simulation.job_*``/
  ``results.ready``/``simulation.failed``) as they
  arrive, until ``--wait-s`` elapses.  Use it in a second terminal after
  ``--submit`` to follow the run.

The MCP server and the cluster simclient use the same Matrix account but log in
separately, so each gets its own MAS session/device and its own refresh chain
(no rotation conflict).  RCP messages are role-tagged, so the self-echo works.

Usage::

    python scripts/local_mcp_check.py --setup
    # ... start scripts/cluster_simclient.sh on the login node ...
    python scripts/local_mcp_check.py --run
    python scripts/local_mcp_check.py --submit --picmi-script ./my_sim.py
    python scripts/local_mcp_check.py --watch
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import secrets
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

from mcp import ClientSession
from mcp.client.stdio import StdioServerParameters, stdio_client

from pic_agentic.auth import MasTokenStore
from pic_agentic.config import Config

DEFAULT_STATE = Path("~/.config/pic-agentic/cluster-check.json").expanduser()
DEFAULT_MESSAGE = "Hello from the MCP server to the cluster"


def api(homeserver: str, method: str, path: str, token: str, data: dict | None = None) -> dict:
    """Call one Matrix client-server endpoint and return the JSON body.

    Returns:
        The decoded response body.

    Raises:
        SystemExit: On an HTTP error, with the server's message.

    """
    body = json.dumps(data).encode() if data is not None else None
    req = urllib.request.Request(homeserver + path, data=body, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=40) as response:
            return json.loads(response.read().decode())
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode(errors="replace")[:300]
        msg = f"{method} {path} failed ({exc.code}): {detail}"
        raise SystemExit(msg) from exc


def cmd_setup(args: argparse.Namespace) -> int:
    """Create the room + secret and print the cluster-side exports.

    Returns:
        The process exit code.

    Raises:
        SystemExit: If no MAS refresh chain is configured or no cluster
            message directory was given.

    """
    config = Config.load()
    if not config.has_refresh_chain():
        msg = "no MAS refresh chain in the config; run scripts/mas_login.py first"
        raise SystemExit(msg)
    if not args.message_dir:
        msg = (
            "set --message-dir to the CLUSTER absolute path for message files "
            "(e.g. /scratch/<user>/pic-agentic/shared); it must match "
            "PIC_AGENTIC_MESSAGE_DIR on the login node"
        )
        raise SystemExit(msg)
    if not args.message_dir.startswith("/"):
        msg = f"--message-dir must be an absolute path: {args.message_dir!r}"
        raise SystemExit(msg)

    async def token() -> str:
        return await MasTokenStore.from_config(config).access_token()

    access = asyncio.run(token())
    who = api(config.homeserver, "GET", "/_matrix/client/v3/account/whoami", access)
    user = who["user_id"]
    room = api(
        config.homeserver,
        "POST",
        "/_matrix/client/v3/createRoom",
        access,
        {"name": "pic-agentic cluster check", "preset": "private_chat"},
    )
    room_id = room["room_id"]
    secret = secrets.token_hex(32)

    state = {
        "homeserver": config.homeserver,
        "room_id": room_id,
        "rcp_secret": secret,
        "user_id": user,
        "sim": args.sim,
        # The message path is generated by the MCP server but written and
        # validated by the simclient, so both must use the SAME absolute path.
        # It is a directory on the CLUSTER (the MCP server only builds the
        # string). Point it at shared storage visible to the compute node.
        "message_dir": args.message_dir,
    }
    args.state.parent.mkdir(parents=True, exist_ok=True)
    args.state.write_text(json.dumps(state, indent=2))
    args.state.chmod(0o600)

    export = (
        f"export PIC_AGENTIC_HOMESERVER='{config.homeserver}'\n"
        f"export PIC_AGENTIC_ROOM_ID='{room_id}'\n"
        f"export PIC_AGENTIC_RCP_SECRET='{secret}'\n"
        f"export PIC_AGENTIC_SIM='{args.sim}'\n"
        f"export PIC_AGENTIC_MESSAGE_DIR='{args.message_dir}'\n"
    )
    print(f"Room created on {config.homeserver} as {user}:")
    print(f"  {room_id}\n")
    print("Copy the repo to the cluster (or let the script clone it), then run:\n")
    print(export)
    print(f"  PIC_AGENTIC_MESSAGE_DIR='{args.message_dir}' bash cluster_simclient.sh")
    print(f"\nState saved to {args.state} (0600). Then run: python scripts/local_mcp_check.py --run")
    return 0


def _server_env(state: dict) -> dict:
    """Build the environment for the MCP stdio server subprocess.

    Returns:
        ``os.environ`` plus the per-run RCP/MCP settings.

    """
    env = dict(os.environ)
    env.update(
        {
            "PIC_AGENTIC_HOMESERVER": state["homeserver"],
            "PIC_AGENTIC_ROOM_ID": state["room_id"],
            "PIC_AGENTIC_RCP_SECRET": state["rcp_secret"],
            "PIC_AGENTIC_SIM": state["sim"],
            # Used by the M1 hello path; the M2 payload travels inline, so this
            # is only the simclient-side bookkeeping directory.
            "PIC_AGENTIC_MESSAGE_DIR": state["message_dir"],
            "PIC_AGENTIC_POLL_INTERVAL_S": "2",
            # The cluster side may wait in the SLURM queue; keep the ack wait
            # generous.  The `accepted` ack is immediate, so this only bounds a
            # missing/unreachable simclient.
            "PIC_AGENTIC_ACK_TIMEOUT_S": str(state.get("ack_timeout_s", 900)),
        }
    )
    # picongpu_python/revision may come from the state file or the environment.
    for key in ("PIC_AGENTIC_PICONGPU_PYTHON", "PIC_AGENTIC_PICONGPU_REVISION"):
        if state.get(key):
            env[key] = state[key]
    return env


async def _call_tool(state: dict, tool: str, arguments: dict) -> dict:
    """Drive the MCP stdio server and call one tool once.

    Returns:
        The tool's structured content.

    """
    params = StdioServerParameters(command=sys.executable, args=["-m", "pic_agentic.server"], env=_server_env(state))
    async with stdio_client(params) as (read, write), ClientSession(read, write) as session:
        await session.initialize()
        result = await session.call_tool(tool, arguments)
        return result.structured_content or {"ok": result.is_error is False}


async def _call_hello(state: dict, message: str) -> dict:
    """Call the ``hello`` tool once.

    Returns:
        The tool's structured content.

    """
    return await _call_tool(state, "hello", {"message": message})


async def _call_submit(state: dict, script_path: str) -> dict:
    """Call the ``submit_simulation`` tool once with a PICMI script path.

    Returns:
        The tool's structured content.

    """
    return await _call_tool(state, "submit_simulation", {"picmi_script": script_path})


def cmd_run(args: argparse.Namespace) -> int:
    """Wait for the cluster simclient, then exercise the hello round trip.

    Returns:
        The process exit code.

    Raises:
        SystemExit: If no setup state exists.

    """
    if not args.state.exists():
        msg = f"no state at {args.state}; run --setup first"
        raise SystemExit(msg)
    state = json.loads(args.state.read_text())
    state["ack_timeout_s"] = args.ack_timeout_s

    deadline = time.monotonic() + args.wait_s
    attempt = 0
    while True:
        attempt += 1
        print(f"[attempt {attempt}] sending hello (per-attempt ack wait {args.ack_timeout_s:.0f}s) ...", flush=True)
        try:
            result = asyncio.run(_call_hello(state, args.message))
        except Exception as exc:  # ruff: ignore[blind-except] - the server reports failure as data normally
            result = {"ok": False, "error": f"{type(exc).__name__}: {exc}"}
        print(json.dumps(result, indent=2), flush=True)
        if result.get("ok") and args.message in (result.get("cluster_output") or ""):
            print("\nCOMMUNICATION OK: the cluster simclient received the command and acked.")
            return 0
        if time.monotonic() >= deadline:
            print("\nFAILED: no successful ack before the wait expired.", file=sys.stderr)
            return 1
        print("no ack yet; is the cluster simclient running? retrying in 15s ...", flush=True)
        time.sleep(15)


def cmd_submit(args: argparse.Namespace) -> int:
    """Drive the MCP server and call the M2 submit_simulation tool once.

    Returns:
        The process exit code.

    Raises:
        SystemExit: If the state or the PICMI script is missing.

    """
    if not args.state.exists():
        msg = f"no state at {args.state}; run --setup first"
        raise SystemExit(msg)
    if not args.picmi_script:
        msg = "--submit requires --picmi-script <path>"
        raise SystemExit(msg)
    script = Path(args.picmi_script).expanduser()
    if not script.is_file():
        msg = f"PICMI script not found: {script}"
        raise SystemExit(msg)
    state = json.loads(args.state.read_text())
    state["ack_timeout_s"] = args.ack_timeout_s
    if args.picongpu_python:
        state["PIC_AGENTIC_PICONGPU_PYTHON"] = args.picongpu_python
    try:
        result = asyncio.run(_call_submit(state, str(script.resolve())))
    except Exception as exc:  # ruff: ignore[blind-except] - the server reports failure as data normally
        result = {"ok": False, "error": f"{type(exc).__name__}: {exc}"}
    print(json.dumps(result, indent=2), flush=True)
    if not result.get("ok"):
        print("\nFAILED: the submit command was not accepted.", file=sys.stderr)
        return 1
    print(f"\nSUBMIT ACCEPTED: sim_id={result.get('sim_id')} state={result.get('state')}")
    print("Watch the room / run --watch to follow the run to results.ready.")
    return 0


def _call_report_tool(state: dict, tool: str, arguments: dict) -> int:
    """Drive the MCP server and call one M2b reporting tool once.

    A fresh server process backfills the room into its registry on startup, so
    ``get_status``/``list_simulations``/``get_events`` see prior history.

    Returns:
        The process exit code.

    """
    try:
        result = asyncio.run(_call_tool(state, tool, arguments))
    except Exception as exc:  # ruff: ignore[blind-except] - surfaced as data normally
        result = {"ok": False, "error": f"{type(exc).__name__}: {exc}"}
    print(json.dumps(result, indent=2, default=str), flush=True)
    return 0 if "error" not in result else 1


def cmd_status(args: argparse.Namespace) -> int:
    """Call ``get_status`` / ``list_simulations`` / ``get_events`` on the room.

    Returns:
        The process exit code.

    Raises:
        SystemExit: If no setup state exists.

    """
    if not args.state.exists():
        msg = f"no state at {args.state}; run --setup first"
        raise SystemExit(msg)
    state = json.loads(args.state.read_text())
    if args.events:
        return _call_report_tool(state, "get_events", {"sim_id": args.sim_id, "limit": 50})
    if args.sim_id:
        return _call_report_tool(state, "get_status", {"sim_id": args.sim_id})
    return _call_report_tool(state, "list_simulations", {"active_only": False})


def cmd_logs(args: argparse.Namespace) -> int:
    """Call ``get_logs`` for one sim on the room.

    Returns:
        The process exit code.

    Raises:
        SystemExit: If no setup state exists.

    """
    if not args.state.exists():
        msg = f"no state at {args.state}; run --setup first"
        raise SystemExit(msg)
    state = json.loads(args.state.read_text())
    return _call_report_tool(state, "get_logs", {"sim_id": args.sim_id, "stream": args.stream, "tail": args.tail})


def cmd_watch(args: argparse.Namespace) -> int:
    """Read the RCP room and print lifecycle events until the wait expires.

    Returns:
        The process exit code (0 on ``results.ready``, 1 on failure/timeout).

    Raises:
        SystemExit: If no setup state exists.

    """
    if not args.state.exists():
        msg = f"no state at {args.state}; run --setup first"
        raise SystemExit(msg)
    state = json.loads(args.state.read_text())
    return asyncio.run(_watch(state, args.wait_s))


async def _watch(state: dict, wait_s: float) -> int:
    from pic_agentic.transport.matrix import (  # ruff: ignore[import-outside-top-level] - lazy transport import
        MatrixTransport,
    )

    config = Config.load()
    token_provider = MasTokenStore.from_config(config).access_token if config.has_refresh_chain() else None
    transport = MatrixTransport(
        state["homeserver"],
        config.user_id or state["user_id"],
        config.access_token,
        state["room_id"],
        store_path=os.environ.get("PIC_AGENTIC_NIO_STORE_DIR") or None,
        token_provider=token_provider,
    )
    seen: set[str] = set()
    deadline = time.monotonic() + wait_s
    try:
        for message in await transport.backfill():
            seen.add(message.transport_event_id or message.dedup_key()[0])
            rc = _print_event(message)
            if rc is not None:
                return rc
        iterator = aiter(transport.receive())
        while True:
            remaining = deadline - time.monotonic()
            if remaining <= 0:
                print("\nNo terminal event before the wait expired.", file=sys.stderr)
                return 1
            try:
                message = await asyncio.wait_for(anext(iterator), timeout=remaining)
            except (TimeoutError, StopAsyncIteration):
                print("\nNo terminal event before the wait expired.", file=sys.stderr)
                return 1
            if message.transport_event_id in seen:
                continue
            seen.add(message.transport_event_id or message.dedup_key()[0])
            rc = _print_event(message)
            if rc is not None:
                return rc
    finally:
        await transport.close()


def _print_event(message) -> int | None:
    if not message.type.startswith("rcp.simulation"):
        return None
    payload = message.payload
    state = payload.get("state")
    job_id = payload.get("job_id")
    detail = ""
    if state == "simulation.step_finished":
        detail = f" step={payload.get('step')} percent={payload.get('percent')} eta_s={payload.get('eta_s')}"
    elif state in {"simulation.job_finished", "simulation.job_failed"}:
        detail = f" slurm_state={payload.get('slurm_state')} exit_code={payload.get('exit_code')}"
    print(f"[{message.type}] state={state} job_id={job_id}{detail}", flush=True)
    error = payload.get("error")
    if error:
        print(f"    error: {error}", flush=True)
    # M2b: `workflow.finished` is no longer terminal (the job may still run).
    # Only `results.ready` (results linked) is success; job/sim failures are not.
    if state == "results.ready":
        linked = payload.get("results_linked")
        print(f"\nRESULTS READY (results linked: {linked}).", flush=True)
        return 0
    if state in {"simulation.failed", "simulation.job_failed"}:
        print("\nSIMULATION FAILED.", file=sys.stderr, flush=True)
        return 1
    return None


def main() -> None:
    """Parse arguments and dispatch to setup, run, submit, or watch.

    Raises:
        SystemExit: With the chosen command's exit code.

    """
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--setup", action="store_true", help="create a room + secret for the cluster run")
    mode.add_argument("--run", action="store_true", help="drive the MCP server and send hello")
    mode.add_argument("--submit", action="store_true", help="drive the MCP server and call submit_simulation")
    mode.add_argument("--watch", action="store_true", help="follow lifecycle events in the RCP room")
    mode.add_argument("--status", action="store_true", help="call get_status / list_simulations / get_events")
    mode.add_argument("--logs", action="store_true", help="call get_logs for one sim")
    parser.add_argument("--state", type=Path, default=DEFAULT_STATE)
    parser.add_argument("--sim", default="cluster")
    parser.add_argument("--message", default=DEFAULT_MESSAGE)
    parser.add_argument("--sim-id", default="", help="sim_id for --status/--logs")
    parser.add_argument("--events", action="store_true", help="with --status: return get_events instead")
    parser.add_argument("--stream", default="stdout", help="log stream for --logs")
    parser.add_argument("--tail", type=int, default=100, help="log lines for --logs")
    parser.add_argument("--picmi-script", default="", help="PICMI script path for --submit")
    parser.add_argument(
        "--picongpu-python",
        default="",
        help=(
            "Interpreter with the [sim] extra that builds the payload subprocess "
            "(PIC_AGENTIC_PICONGPU_PYTHON); defaults to the server's interpreter."
        ),
    )
    parser.add_argument("--wait-s", type=float, default=1800.0, help="overall wait for an ack")
    parser.add_argument("--ack-timeout-s", type=float, default=900.0, help="per-attempt ack wait")
    parser.add_argument(
        "--message-dir",
        default="",
        help=(
            "CLUSTER-side absolute directory for message files (must match "
            "PIC_AGENTIC_MESSAGE_DIR / the default on the login node; e.g. "
            "/scratch/<user>/pic-agentic/shared). Required for --setup."
        ),
    )
    args = parser.parse_args()
    if args.setup:
        raise SystemExit(cmd_setup(args))
    if args.submit:
        raise SystemExit(cmd_submit(args))
    if args.watch:
        raise SystemExit(cmd_watch(args))
    if args.status:
        raise SystemExit(cmd_status(args))
    if args.logs:
        raise SystemExit(cmd_logs(args))
    raise SystemExit(cmd_run(args))


if __name__ == "__main__":
    main()
